name: TipsAuto

on:
  # Executa automaticamente a cada 1 minuto (UTC)
  schedule:
    - cron: "*/1 * * * *"
  # Permite execução manual via GitHub Actions
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Debug time
        run: |
          echo "Hora local do runner:"
          date
          echo "Hora UTC:"
          date -u

      - name: Run script
        run: python GeraTips.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
