name: Executar script Python Tips

on:
  schedule:
    - cron: "0 11 * * *"   # 06:00 Brasil
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Instalar dependÃªncias
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Executar script
        run: |
          python GeraTips.py
